`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Apr 18 2022 07:22:29 CST (Apr 17 2022 23:22:29 UTC)

module dut_Add_2U_15_4(in1, out1);
  input [1:0] in1;
  output [1:0] out1;
  wire [1:0] in1;
  wire [1:0] out1;
  assign out1[0] = in1[0];
  assign out1[1] = in1[1];
endmodule


