`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Apr 17 2022 22:17:29 CST (Apr 17 2022 14:17:29 UTC)

module dut_OrReduction_3U_1U_1(in1, out1);
  input [2:0] in1;
  output out1;
  wire [2:0] in1;
  wire out1;
  wire n_0;
  NAND2BX2 g6(.AN (in1[0]), .B (n_0), .Y (out1));
  NOR2X4 g7(.A (in1[2]), .B (in1[1]), .Y (n_0));
endmodule


