`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Apr 18 2022 07:22:19 CST (Apr 17 2022 23:22:19 UTC)

module dut_GreaterThanEQ_8Ux8U_1U_1(in2, in1, out1);
  input [7:0] in2, in1;
  output out1;
  wire [7:0] in2, in1;
  wire out1;
  wire lte_21_21_n_0, lte_21_21_n_1, lte_21_21_n_2, lte_21_21_n_3,
       lte_21_21_n_4, lte_21_21_n_5, lte_21_21_n_6, lte_21_21_n_7;
  wire lte_21_21_n_8, lte_21_21_n_9, lte_21_21_n_10, lte_21_21_n_11,
       lte_21_21_n_12, lte_21_21_n_13, lte_21_21_n_14, lte_21_21_n_15;
  wire lte_21_21_n_16, lte_21_21_n_17, lte_21_21_n_18, lte_21_21_n_19,
       lte_21_21_n_20, lte_21_21_n_21, lte_21_21_n_22, lte_21_21_n_23;
  wire lte_21_21_n_24, lte_21_21_n_25, lte_21_21_n_26, lte_21_21_n_27,
       lte_21_21_n_28, lte_21_21_n_29, lte_21_21_n_30, lte_21_21_n_31;
  wire lte_21_21_n_32;
  NAND2X1 lte_21_21_g138(.A (lte_21_21_n_31), .B (lte_21_21_n_32), .Y
       (out1));
  OAI21X1 lte_21_21_g139(.A0 (lte_21_21_n_26), .A1 (lte_21_21_n_30),
       .B0 (lte_21_21_n_25), .Y (lte_21_21_n_32));
  AOI2BB1X1 lte_21_21_g140(.A0N (lte_21_21_n_23), .A1N
       (lte_21_21_n_27), .B0 (lte_21_21_n_28), .Y (lte_21_21_n_31));
  NOR2X1 lte_21_21_g141(.A (lte_21_21_n_24), .B (lte_21_21_n_29), .Y
       (lte_21_21_n_30));
  AOI21X1 lte_21_21_g142(.A0 (lte_21_21_n_0), .A1 (lte_21_21_n_12), .B0
       (lte_21_21_n_13), .Y (lte_21_21_n_29));
  NAND2X1 lte_21_21_g143(.A (lte_21_21_n_15), .B (lte_21_21_n_20), .Y
       (lte_21_21_n_28));
  AOI21X1 lte_21_21_g144(.A0 (lte_21_21_n_2), .A1 (lte_21_21_n_10), .B0
       (lte_21_21_n_16), .Y (lte_21_21_n_27));
  NAND2X1 lte_21_21_g145(.A (lte_21_21_n_8), .B (lte_21_21_n_21), .Y
       (lte_21_21_n_26));
  NOR2X1 lte_21_21_g146(.A (lte_21_21_n_23), .B (lte_21_21_n_22), .Y
       (lte_21_21_n_25));
  NAND2X1 lte_21_21_g147(.A (lte_21_21_n_18), .B (lte_21_21_n_9), .Y
       (lte_21_21_n_24));
  NAND2X1 lte_21_21_g148(.A (lte_21_21_n_19), .B (lte_21_21_n_1), .Y
       (lte_21_21_n_23));
  NAND2X1 lte_21_21_g149(.A (lte_21_21_n_2), .B (lte_21_21_n_17), .Y
       (lte_21_21_n_22));
  NAND2X1 lte_21_21_g150(.A (lte_21_21_n_18), .B (lte_21_21_n_11), .Y
       (lte_21_21_n_21));
  NAND2X1 lte_21_21_g151(.A (lte_21_21_n_19), .B (lte_21_21_n_14), .Y
       (lte_21_21_n_20));
  NAND2X1 lte_21_21_g152(.A (in1[4]), .B (lte_21_21_n_6), .Y
       (lte_21_21_n_17));
  NOR2BX1 lte_21_21_g153(.AN (in2[5]), .B (in1[5]), .Y
       (lte_21_21_n_16));
  NAND2BXL lte_21_21_g154(.AN (in1[7]), .B (in2[7]), .Y
       (lte_21_21_n_15));
  NOR2BX1 lte_21_21_g155(.AN (in2[6]), .B (in1[6]), .Y
       (lte_21_21_n_14));
  NAND2X1 lte_21_21_g157(.A (in1[7]), .B (lte_21_21_n_7), .Y
       (lte_21_21_n_19));
  NAND2X2 lte_21_21_g158(.A (in1[3]), .B (lte_21_21_n_5), .Y
       (lte_21_21_n_18));
  NOR2X1 lte_21_21_g160(.A (lte_21_21_n_4), .B (in1[1]), .Y
       (lte_21_21_n_13));
  NAND2X1 lte_21_21_g161(.A (in1[1]), .B (lte_21_21_n_4), .Y
       (lte_21_21_n_12));
  NOR2X1 lte_21_21_g162(.A (lte_21_21_n_3), .B (in1[2]), .Y
       (lte_21_21_n_11));
  NOR2X1 lte_21_21_g163(.A (lte_21_21_n_6), .B (in1[4]), .Y
       (lte_21_21_n_10));
  NAND2X1 lte_21_21_g164(.A (in1[2]), .B (lte_21_21_n_3), .Y
       (lte_21_21_n_9));
  NAND2BXL lte_21_21_g166(.AN (in1[3]), .B (in2[3]), .Y
       (lte_21_21_n_8));
  INVX1 lte_21_21_g169(.A (in2[7]), .Y (lte_21_21_n_7));
  INVX1 lte_21_21_g171(.A (in2[4]), .Y (lte_21_21_n_6));
  INVX1 lte_21_21_g172(.A (in2[3]), .Y (lte_21_21_n_5));
  INVX1 lte_21_21_g173(.A (in2[1]), .Y (lte_21_21_n_4));
  INVX1 lte_21_21_g174(.A (in2[2]), .Y (lte_21_21_n_3));
  NAND2BX1 lte_21_21_g2(.AN (in2[5]), .B (in1[5]), .Y (lte_21_21_n_2));
  NAND2BX1 lte_21_21_g175(.AN (in2[6]), .B (in1[6]), .Y
       (lte_21_21_n_1));
  NAND2BX1 lte_21_21_g176(.AN (in2[0]), .B (in1[0]), .Y
       (lte_21_21_n_0));
endmodule


