`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Apr 18 2022 07:11:19 CST (Apr 17 2022 23:11:19 UTC)

module dut_Eqi3u3_1(in1, out1);
  input [2:0] in1;
  output out1;
  wire [2:0] in1;
  wire out1;
  wire n_0, n_1;
  NOR2BX2 g14(.AN (in1[0]), .B (n_1), .Y (out1));
  NAND2X6 g15(.A (in1[1]), .B (n_0), .Y (n_1));
  CLKINVX12 g16(.A (in1[2]), .Y (n_0));
endmodule


