`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Apr 18 2022 07:11:18 CST (Apr 17 2022 23:11:18 UTC)

module dut_Eqi4u3_1(in1, out1);
  input [2:0] in1;
  output out1;
  wire [2:0] in1;
  wire out1;
  wire n_0;
  NOR3X6 g16(.A (in1[0]), .B (in1[1]), .C (n_0), .Y (out1));
  CLKINVX4 g17(.A (in1[2]), .Y (n_0));
endmodule


