`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Apr 18 2022 07:22:19 CST (Apr 17 2022 23:22:19 UTC)

module dut_N_Mux_8_3_8_1(in4, in3, in2, ctrl1, out1);
  input [7:0] in4, in3, in2;
  input [2:0] ctrl1;
  output [7:0] out1;
  wire [7:0] in4, in3, in2;
  wire [2:0] ctrl1;
  wire [7:0] out1;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_36;
  OAI21X1 g154(.A0 (n_1), .A1 (n_36), .B0 (n_22), .Y (out1[5]));
  OAI21X1 g150(.A0 (n_3), .A1 (n_36), .B0 (n_25), .Y (out1[6]));
  OAI21X1 g151(.A0 (n_7), .A1 (n_36), .B0 (n_26), .Y (out1[7]));
  OAI21X1 g149(.A0 (n_0), .A1 (n_36), .B0 (n_24), .Y (out1[4]));
  OAI21X1 g156(.A0 (n_5), .A1 (n_36), .B0 (n_29), .Y (out1[1]));
  OAI21X1 g153(.A0 (n_6), .A1 (n_36), .B0 (n_21), .Y (out1[2]));
  OAI21X1 g155(.A0 (n_4), .A1 (n_36), .B0 (n_28), .Y (out1[3]));
  OAI21X1 g152(.A0 (n_2), .A1 (n_36), .B0 (n_23), .Y (out1[0]));
  AOI21X1 g164(.A0 (in3[1]), .A1 (n_27), .B0 (n_17), .Y (n_29));
  AOI21X1 g160(.A0 (in3[3]), .A1 (n_27), .B0 (n_15), .Y (n_28));
  AOI21X1 g163(.A0 (in3[7]), .A1 (n_27), .B0 (n_18), .Y (n_26));
  AOI21X1 g157(.A0 (in3[6]), .A1 (n_27), .B0 (n_16), .Y (n_25));
  AOI21X1 g158(.A0 (in3[4]), .A1 (n_27), .B0 (n_13), .Y (n_24));
  AOI21X1 g159(.A0 (in3[0]), .A1 (n_27), .B0 (n_14), .Y (n_23));
  AOI21X1 g161(.A0 (in3[5]), .A1 (n_27), .B0 (n_20), .Y (n_22));
  AOI21X1 g162(.A0 (in3[2]), .A1 (n_27), .B0 (n_12), .Y (n_21));
  NAND2X4 g173(.A (n_19), .B (n_11), .Y (n_36));
  NOR2BX1 g172(.AN (in2[5]), .B (n_19), .Y (n_20));
  NOR2BX1 g171(.AN (in2[7]), .B (n_19), .Y (n_18));
  NOR2BX1 g170(.AN (in2[1]), .B (n_19), .Y (n_17));
  NOR2BX1 g165(.AN (in2[6]), .B (n_19), .Y (n_16));
  NOR2BX1 g168(.AN (in2[3]), .B (n_19), .Y (n_15));
  NOR2BX1 g167(.AN (in2[0]), .B (n_19), .Y (n_14));
  NOR2BX1 g166(.AN (in2[4]), .B (n_19), .Y (n_13));
  NOR2BX1 g169(.AN (in2[2]), .B (n_19), .Y (n_12));
  CLKINVX3 g175(.A (n_27), .Y (n_11));
  NAND2X8 g174(.A (ctrl1[0]), .B (n_9), .Y (n_19));
  NOR2X6 g176(.A (ctrl1[0]), .B (n_10), .Y (n_27));
  NAND2X8 g177(.A (ctrl1[2]), .B (n_8), .Y (n_10));
  NOR2X8 g178(.A (ctrl1[2]), .B (n_8), .Y (n_9));
  INVX1 g185(.A (in4[7]), .Y (n_7));
  INVX1 g181(.A (in4[2]), .Y (n_6));
  INVX1 g187(.A (in4[1]), .Y (n_5));
  INVX1 g186(.A (in4[3]), .Y (n_4));
  INVX1 g179(.A (in4[6]), .Y (n_3));
  INVX1 g182(.A (in4[0]), .Y (n_2));
  INVX1 g184(.A (in4[5]), .Y (n_1));
  INVX1 g180(.A (in4[4]), .Y (n_0));
  CLKINVX12 g183(.A (ctrl1[1]), .Y (n_8));
endmodule


