`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Apr 17 2022 22:24:04 CST (Apr 17 2022 14:24:04 UTC)

module dut_Lti8s32_4(in1, out1);
  input [31:0] in1;
  output out1;
  wire [31:0] in1;
  wire out1;
  wire gt_19_105_n_0, gt_19_105_n_1, gt_19_105_n_2, gt_19_105_n_3,
       gt_19_105_n_4, gt_19_105_n_5, gt_19_105_n_6, gt_19_105_n_7;
  wire gt_19_105_n_8, gt_19_105_n_9;
  NAND2BX1 gt_19_105_g561(.AN (in1[31]), .B (gt_19_105_n_9), .Y (out1));
  NAND4XL gt_19_105_g562(.A (gt_19_105_n_4), .B (gt_19_105_n_2), .C
       (gt_19_105_n_5), .D (gt_19_105_n_8), .Y (gt_19_105_n_9));
  NOR4X1 gt_19_105_g563(.A (gt_19_105_n_0), .B (gt_19_105_n_7), .C
       (in1[3]), .D (gt_19_105_n_6), .Y (gt_19_105_n_8));
  NAND2X1 gt_19_105_g564(.A (gt_19_105_n_3), .B (gt_19_105_n_1), .Y
       (gt_19_105_n_7));
  OR4X1 gt_19_105_g565(.A (in1[7]), .B (in1[6]), .C (in1[5]), .D
       (in1[4]), .Y (gt_19_105_n_6));
  NOR4X1 gt_19_105_g566(.A (in1[31]), .B (in1[30]), .C (in1[29]), .D
       (in1[28]), .Y (gt_19_105_n_5));
  NOR4X1 gt_19_105_g567(.A (in1[27]), .B (in1[26]), .C (in1[25]), .D
       (in1[24]), .Y (gt_19_105_n_4));
  NOR4X1 gt_19_105_g568(.A (in1[15]), .B (in1[14]), .C (in1[13]), .D
       (in1[12]), .Y (gt_19_105_n_3));
  NOR4X1 gt_19_105_g569(.A (in1[23]), .B (in1[22]), .C (in1[21]), .D
       (in1[20]), .Y (gt_19_105_n_2));
  NOR4X1 gt_19_105_g570(.A (in1[11]), .B (in1[10]), .C (in1[9]), .D
       (in1[8]), .Y (gt_19_105_n_1));
  OR4X1 gt_19_105_g571(.A (in1[19]), .B (in1[18]), .C (in1[17]), .D
       (in1[16]), .Y (gt_19_105_n_0));
endmodule


