`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Apr 18 2022 07:11:17 CST (Apr 17 2022 23:11:17 UTC)

module dut_Eqi7u3_1(in1, out1);
  input [2:0] in1;
  output out1;
  wire [2:0] in1;
  wire out1;
  wire n_0;
  NOR2BX2 g10(.AN (in1[0]), .B (n_0), .Y (out1));
  NAND2X4 g11(.A (in1[2]), .B (in1[1]), .Y (n_0));
endmodule


