`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Apr 18 2022 07:22:09 CST (Apr 17 2022 23:22:09 UTC)

module dut_N_Mux_8_3_8_4(in4, in3, in2, ctrl1, out1);
  input [7:0] in4, in3, in2;
  input [2:0] ctrl1;
  output [7:0] out1;
  wire [7:0] in4, in3, in2;
  wire [2:0] ctrl1;
  wire [7:0] out1;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_17;
  OAI2BB1X1 g155(.A0N (in4[3]), .A1N (n_17), .B0 (n_2), .Y (out1[3]));
  OAI2BB1X1 g149(.A0N (in4[4]), .A1N (n_17), .B0 (n_9), .Y (out1[4]));
  OAI2BB1X1 g151(.A0N (in4[7]), .A1N (n_17), .B0 (n_3), .Y (out1[7]));
  OAI2BB1X1 g153(.A0N (in4[2]), .A1N (n_17), .B0 (n_5), .Y (out1[2]));
  OAI2BB1X1 g150(.A0N (in4[6]), .A1N (n_17), .B0 (n_6), .Y (out1[6]));
  OAI2BB1X1 g152(.A0N (in4[0]), .A1N (n_17), .B0 (n_10), .Y (out1[0]));
  OAI2BB1X1 g156(.A0N (in4[1]), .A1N (n_17), .B0 (n_4), .Y (out1[1]));
  OAI2BB1X1 g154(.A0N (in4[5]), .A1N (n_17), .B0 (n_1), .Y (out1[5]));
  AOI22X1 g159(.A0 (in3[0]), .A1 (n_8), .B0 (in2[0]), .B1 (n_7), .Y
       (n_10));
  AOI22X1 g158(.A0 (in3[4]), .A1 (n_8), .B0 (in2[4]), .B1 (n_7), .Y
       (n_9));
  AOI22X1 g157(.A0 (in3[6]), .A1 (n_8), .B0 (in2[6]), .B1 (n_7), .Y
       (n_6));
  AOI22X1 g162(.A0 (in3[2]), .A1 (n_8), .B0 (in2[2]), .B1 (n_7), .Y
       (n_5));
  AOI22X1 g164(.A0 (in3[1]), .A1 (n_8), .B0 (in2[1]), .B1 (n_7), .Y
       (n_4));
  AOI22X1 g163(.A0 (in3[7]), .A1 (n_8), .B0 (in2[7]), .B1 (n_7), .Y
       (n_3));
  AOI22X1 g160(.A0 (in3[3]), .A1 (n_8), .B0 (in2[3]), .B1 (n_7), .Y
       (n_2));
  AOI22X1 g161(.A0 (in3[5]), .A1 (n_8), .B0 (in2[5]), .B1 (n_7), .Y
       (n_1));
  NOR2X1 g165(.A (n_7), .B (n_8), .Y (n_17));
  AND3XL g166(.A (ctrl1[0]), .B (ctrl1[1]), .C (n_0), .Y (n_7));
  NOR3X1 g167(.A (ctrl1[0]), .B (n_0), .C (ctrl1[1]), .Y (n_8));
  INVX1 g168(.A (ctrl1[2]), .Y (n_0));
endmodule


