`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Apr 18 2022 07:22:18 CST (Apr 17 2022 23:22:18 UTC)

module dut_N_Mux_8_4_9_1(in5, in4, in3, in2, ctrl1, out1);
  input [7:0] in5, in4, in3, in2;
  input [2:0] ctrl1;
  output [7:0] out1;
  wire [7:0] in5, in4, in3, in2;
  wire [2:0] ctrl1;
  wire [7:0] out1;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  NAND2X1 g184(.A (n_32), .B (n_37), .Y (out1[5]));
  NAND2X1 g185(.A (n_35), .B (n_43), .Y (out1[6]));
  NAND2X1 g186(.A (n_45), .B (n_31), .Y (out1[7]));
  NAND2X1 g189(.A (n_30), .B (n_39), .Y (out1[4]));
  NAND2X1 g190(.A (n_33), .B (n_41), .Y (out1[1]));
  NAND2X1 g187(.A (n_34), .B (n_36), .Y (out1[2]));
  NAND2X1 g191(.A (n_40), .B (n_38), .Y (out1[3]));
  NAND2X1 g188(.A (n_46), .B (n_47), .Y (out1[0]));
  AOI21X1 g205(.A0 (in3[0]), .A1 (n_42), .B0 (n_23), .Y (n_47));
  AOI2BB1X1 g195(.A0N (n_4), .A1N (n_44), .B0 (n_16), .Y (n_46));
  AOI2BB1X1 g198(.A0N (n_1), .A1N (n_44), .B0 (n_20), .Y (n_45));
  AOI21X1 g204(.A0 (in3[6]), .A1 (n_42), .B0 (n_26), .Y (n_43));
  AOI21X1 g203(.A0 (in3[1]), .A1 (n_42), .B0 (n_28), .Y (n_41));
  AOI2BB1X1 g199(.A0N (n_7), .A1N (n_44), .B0 (n_15), .Y (n_40));
  AOI21X1 g206(.A0 (in3[4]), .A1 (n_42), .B0 (n_29), .Y (n_39));
  AOI21X1 g207(.A0 (in3[3]), .A1 (n_42), .B0 (n_24), .Y (n_38));
  AOI21X1 g201(.A0 (in3[5]), .A1 (n_42), .B0 (n_25), .Y (n_37));
  AOI21X1 g200(.A0 (in3[2]), .A1 (n_42), .B0 (n_22), .Y (n_36));
  AOI2BB1X1 g196(.A0N (n_5), .A1N (n_44), .B0 (n_19), .Y (n_35));
  AOI2BB1X1 g194(.A0N (n_0), .A1N (n_44), .B0 (n_14), .Y (n_34));
  AOI2BB1X1 g192(.A0N (n_2), .A1N (n_44), .B0 (n_13), .Y (n_33));
  AOI2BB1X1 g193(.A0N (n_6), .A1N (n_44), .B0 (n_17), .Y (n_32));
  AOI21X1 g202(.A0 (in3[7]), .A1 (n_42), .B0 (n_21), .Y (n_31));
  AOI2BB1X1 g197(.A0N (n_3), .A1N (n_44), .B0 (n_12), .Y (n_30));
  NOR2BX1 g223(.AN (in4[4]), .B (n_27), .Y (n_29));
  NOR2BX1 g221(.AN (in4[1]), .B (n_27), .Y (n_28));
  NOR2BX1 g220(.AN (in4[6]), .B (n_27), .Y (n_26));
  NOR2BX1 g209(.AN (in4[5]), .B (n_27), .Y (n_25));
  NOR2BX1 g216(.AN (in4[3]), .B (n_27), .Y (n_24));
  NOR2BX1 g215(.AN (in4[0]), .B (n_27), .Y (n_23));
  NOR2BX1 g212(.AN (in4[2]), .B (n_27), .Y (n_22));
  NOR2BX1 g218(.AN (in4[7]), .B (n_27), .Y (n_21));
  NOR2BX1 g222(.AN (in2[7]), .B (n_18), .Y (n_20));
  NOR2BX1 g219(.AN (in2[6]), .B (n_18), .Y (n_19));
  NOR2BX1 g208(.AN (in2[5]), .B (n_18), .Y (n_17));
  NAND2X4 g224(.A (n_11), .B (n_18), .Y (n_44));
  NOR2BX1 g213(.AN (in2[0]), .B (n_18), .Y (n_16));
  NOR2BX1 g211(.AN (in2[3]), .B (n_18), .Y (n_15));
  NOR2BX1 g210(.AN (in2[2]), .B (n_18), .Y (n_14));
  NOR2BX1 g214(.AN (in2[1]), .B (n_18), .Y (n_13));
  NOR2BX1 g217(.AN (in2[4]), .B (n_18), .Y (n_12));
  NAND2X8 g225(.A (ctrl1[0]), .B (n_10), .Y (n_27));
  NAND2X8 g227(.A (ctrl1[0]), .B (n_9), .Y (n_18));
  NOR2X2 g226(.A (ctrl1[0]), .B (n_11), .Y (n_42));
  CLKINVX4 g229(.A (n_11), .Y (n_10));
  NOR2X8 g228(.A (ctrl1[2]), .B (n_8), .Y (n_9));
  NAND2X8 g230(.A (ctrl1[2]), .B (n_8), .Y (n_11));
  INVX1 g238(.A (in5[3]), .Y (n_7));
  INVX1 g232(.A (in5[5]), .Y (n_6));
  INVX1 g237(.A (in5[6]), .Y (n_5));
  CLKINVX12 g239(.A (ctrl1[1]), .Y (n_8));
  INVX1 g233(.A (in5[0]), .Y (n_4));
  INVX1 g236(.A (in5[4]), .Y (n_3));
  INVX1 g235(.A (in5[1]), .Y (n_2));
  INVX1 g234(.A (in5[7]), .Y (n_1));
  INVX1 g231(.A (in5[2]), .Y (n_0));
endmodule


