`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Apr 18 2022 08:24:41 CST (Apr 18 2022 00:24:41 UTC)

module dut_Muxn4i3u1_4(ctrl1, out1);
  input ctrl1;
  output [2:0] out1;
  wire ctrl1;
  wire [2:0] out1;
  assign out1[0] = out1[1];
  assign out1[2] = ctrl1;
  INVX1 g3(.A (ctrl1), .Y (out1[1]));
endmodule


