`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Apr 18 2022 07:11:15 CST (Apr 17 2022 23:11:15 UTC)

module dut_Eqi2u3_4(in1, out1);
  input [2:0] in1;
  output out1;
  wire [2:0] in1;
  wire out1;
  NOR3BX1 g15(.AN (in1[1]), .B (in1[0]), .C (in1[2]), .Y (out1));
endmodule


