`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Apr 18 2022 08:25:41 CST (Apr 18 2022 00:25:41 UTC)

module dut_N_Mux_3_2_23_0(in2, ctrl1, out1);
  input [2:0] in2;
  input ctrl1;
  output [2:0] out1;
  wire [2:0] in2;
  wire ctrl1;
  wire [2:0] out1;
  wire n_0, n_1, n_2, n_11, n_13;
  NAND2X4 g7(.A (n_0), .B (n_11), .Y (out1[2]));
  NAND2X4 g8(.A (n_2), .B (n_13), .Y (out1[1]));
  NAND2X4 g9(.A (n_1), .B (n_11), .Y (out1[0]));
  INVX8 g10(.A (in2[1]), .Y (n_2));
  INVX8 g13(.A (in2[0]), .Y (n_1));
  INVX8 g12(.A (in2[2]), .Y (n_0));
  CLKINVX6 fopt(.A (ctrl1), .Y (n_11));
  CLKINVX4 fopt15(.A (ctrl1), .Y (n_13));
endmodule


