`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Apr 18 2022 07:22:09 CST (Apr 17 2022 23:22:09 UTC)

module dut_GreaterThanEQ_8Ux8U_1U_4(in2, in1, out1);
  input [7:0] in2, in1;
  output out1;
  wire [7:0] in2, in1;
  wire out1;
  wire lte_21_21_n_0, lte_21_21_n_1, lte_21_21_n_2, lte_21_21_n_3,
       lte_21_21_n_4, lte_21_21_n_5, lte_21_21_n_6, lte_21_21_n_7;
  wire lte_21_21_n_8, lte_21_21_n_9, lte_21_21_n_10, lte_21_21_n_11,
       lte_21_21_n_12, lte_21_21_n_13, lte_21_21_n_14, lte_21_21_n_15;
  wire lte_21_21_n_16, lte_21_21_n_17, lte_21_21_n_18, lte_21_21_n_19,
       lte_21_21_n_20, lte_21_21_n_21;
  NAND4XL lte_21_21_g212(.A (lte_21_21_n_21), .B (lte_21_21_n_14), .C
       (lte_21_21_n_7), .D (lte_21_21_n_18), .Y (out1));
  NAND4XL lte_21_21_g213(.A (lte_21_21_n_9), .B (lte_21_21_n_11), .C
       (lte_21_21_n_6), .D (lte_21_21_n_20), .Y (lte_21_21_n_21));
  OAI211X1 lte_21_21_g214(.A0 (lte_21_21_n_1), .A1 (in1[3]), .B0
       (lte_21_21_n_13), .C0 (lte_21_21_n_19), .Y (lte_21_21_n_20));
  OAI211X1 lte_21_21_g215(.A0 (lte_21_21_n_4), .A1 (in2[2]), .B0
       (lte_21_21_n_10), .C0 (lte_21_21_n_17), .Y (lte_21_21_n_19));
  NAND2X1 lte_21_21_g216(.A (lte_21_21_n_11), .B (lte_21_21_n_16), .Y
       (lte_21_21_n_18));
  OAI22X1 lte_21_21_g217(.A0 (in1[1]), .A1 (lte_21_21_n_12), .B0
       (lte_21_21_n_0), .B1 (lte_21_21_n_8), .Y (lte_21_21_n_17));
  OAI2BB1X1 lte_21_21_g218(.A0N (in2[5]), .A1N (lte_21_21_n_3), .B0
       (lte_21_21_n_15), .Y (lte_21_21_n_16));
  NAND3BXL lte_21_21_g219(.AN (in1[4]), .B (in2[4]), .C
       (lte_21_21_n_9), .Y (lte_21_21_n_15));
  NAND3BXL lte_21_21_g220(.AN (in1[6]), .B (in2[6]), .C
       (lte_21_21_n_5), .Y (lte_21_21_n_14));
  NAND3X1 lte_21_21_g221(.A (in2[2]), .B (lte_21_21_n_4), .C
       (lte_21_21_n_10), .Y (lte_21_21_n_13));
  AND2XL lte_21_21_g222(.A (lte_21_21_n_0), .B (lte_21_21_n_8), .Y
       (lte_21_21_n_12));
  OA21X1 lte_21_21_g223(.A0 (lte_21_21_n_2), .A1 (in2[6]), .B0
       (lte_21_21_n_5), .Y (lte_21_21_n_11));
  NAND2X1 lte_21_21_g224(.A (in1[3]), .B (lte_21_21_n_1), .Y
       (lte_21_21_n_10));
  NAND2BX1 lte_21_21_g225(.AN (in2[5]), .B (in1[5]), .Y
       (lte_21_21_n_9));
  NOR2BX1 lte_21_21_g226(.AN (in1[0]), .B (in2[0]), .Y (lte_21_21_n_8));
  NAND2BXL lte_21_21_g227(.AN (in1[7]), .B (in2[7]), .Y
       (lte_21_21_n_7));
  NAND2BX1 lte_21_21_g228(.AN (in2[4]), .B (in1[4]), .Y
       (lte_21_21_n_6));
  NAND2BXL lte_21_21_g229(.AN (in2[7]), .B (in1[7]), .Y
       (lte_21_21_n_5));
  INVX1 lte_21_21_g230(.A (in1[2]), .Y (lte_21_21_n_4));
  INVX1 lte_21_21_g231(.A (in1[5]), .Y (lte_21_21_n_3));
  INVXL lte_21_21_g232(.A (in1[6]), .Y (lte_21_21_n_2));
  INVX1 lte_21_21_g233(.A (in2[3]), .Y (lte_21_21_n_1));
  INVX1 lte_21_21_g234(.A (in2[1]), .Y (lte_21_21_n_0));
endmodule


