`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Apr 18 2022 07:22:20 CST (Apr 17 2022 23:22:20 UTC)

module dut_N_Mux_3_2_6_1(in2, ctrl1, out1);
  input [2:0] in2;
  input ctrl1;
  output [2:0] out1;
  wire [2:0] in2;
  wire ctrl1;
  wire [2:0] out1;
  wire n_0, n_1, n_2, n_4;
  NAND2X4 g7(.A (n_0), .B (n_4), .Y (out1[2]));
  NAND2X4 g8(.A (n_2), .B (n_4), .Y (out1[1]));
  NAND2X4 g9(.A (n_1), .B (n_4), .Y (out1[0]));
  CLKINVX12 g10(.A (in2[1]), .Y (n_2));
  CLKINVX12 g13(.A (in2[0]), .Y (n_1));
  CLKINVX12 g12(.A (in2[2]), .Y (n_0));
  CLKINVX12 g11(.A (ctrl1), .Y (n_4));
endmodule


