`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Apr 17 2022 21:30:40 CST (Apr 17 2022 13:30:40 UTC)

module dut_Add_3Ux2S_5S_4(in2, in1, out1);
  input [2:0] in2;
  input [1:0] in1;
  output [4:0] out1;
  wire [2:0] in2;
  wire [1:0] in1;
  wire [4:0] out1;
  wire add_23_2_n_0, add_23_2_n_1, add_23_2_n_3, add_23_2_n_6;
  AO21XL add_23_2_g93(.A0 (add_23_2_n_0), .A1 (add_23_2_n_6), .B0
       (out1[4]), .Y (out1[3]));
  NOR2X1 add_23_2_g94(.A (add_23_2_n_0), .B (add_23_2_n_6), .Y
       (out1[4]));
  ADDFX1 add_23_2_g95(.A (add_23_2_n_3), .B (in1[1]), .CI (in2[2]), .CO
       (add_23_2_n_6), .S (out1[2]));
  ADDFX1 add_23_2_g96(.A (add_23_2_n_1), .B (in1[1]), .CI (in2[1]), .CO
       (add_23_2_n_3), .S (out1[1]));
  ADDHX1 add_23_2_g97(.A (in2[0]), .B (in1[0]), .CO (add_23_2_n_1), .S
       (out1[0]));
  INVX1 add_23_2_g98(.A (in1[1]), .Y (add_23_2_n_0));
endmodule


