`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Apr 18 2022 07:22:17 CST (Apr 17 2022 23:22:17 UTC)

module dut_N_Mux_8_5_10_1(in6, in5, in4, in3, in2, ctrl1, out1);
  input [7:0] in6, in5, in4, in3, in2;
  input [2:0] ctrl1;
  output [7:0] out1;
  wire [7:0] in6, in5, in4, in3, in2;
  wire [2:0] ctrl1;
  wire [7:0] out1;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_7, n_9;
  wire n_10, n_11, n_12, n_13, n_14, n_15, n_16, n_17;
  wire n_18, n_19, n_20, n_21, n_22, n_23, n_24, n_25;
  wire n_26, n_27, n_28, n_29, n_30, n_31, n_32, n_33;
  wire n_34, n_35, n_36, n_37, n_38, n_39, n_40, n_41;
  wire n_42, n_43, n_44, n_45, n_46, n_47, n_48, n_49;
  wire n_50, n_51, n_52, n_53, n_54, n_55, n_107, n_108;
  wire n_109, n_110, n_111, n_112, n_116, n_117, n_119, n_120;
  wire n_121, n_122;
  NAND2X1 g179(.A (n_22), .B (n_53), .Y (out1[5]));
  NAND2X1 g181(.A (n_33), .B (n_51), .Y (out1[6]));
  NAND2X1 g182(.A (n_25), .B (n_48), .Y (out1[7]));
  NAND2X1 g185(.A (n_20), .B (n_55), .Y (out1[4]));
  NAND2X1 g183(.A (n_27), .B (n_54), .Y (out1[1]));
  NAND2X1 g180(.A (n_34), .B (n_52), .Y (out1[2]));
  NAND2X1 g184(.A (n_18), .B (n_50), .Y (out1[3]));
  NAND2X1 g186(.A (n_19), .B (n_49), .Y (out1[0]));
  NOR3X2 g194(.A (n_10), .B (n_35), .C (n_41), .Y (n_55));
  NOR3BX2 g193(.AN (n_14), .B (n_23), .C (n_39), .Y (n_54));
  NOR3X2 g190(.A (n_9), .B (n_26), .C (n_44), .Y (n_53));
  NOR3BX2 g187(.AN (n_12), .B (n_37), .C (n_46), .Y (n_52));
  NOR3BX2 g188(.AN (n_16), .B (n_38), .C (n_40), .Y (n_51));
  NOR3X2 g189(.A (n_30), .B (n_28), .C (n_43), .Y (n_50));
  NOR3BX2 g191(.AN (n_17), .B (n_24), .C (n_47), .Y (n_49));
  NOR3X2 g192(.A (n_11), .B (n_29), .C (n_42), .Y (n_48));
  NOR2BX1 g202(.AN (in6[0]), .B (n_45), .Y (n_47));
  NOR2BX1 g201(.AN (in6[2]), .B (n_45), .Y (n_46));
  NOR2BX1 g200(.AN (in6[5]), .B (n_45), .Y (n_44));
  NOR2BX1 g195(.AN (in6[3]), .B (n_45), .Y (n_43));
  NOR2BX1 g198(.AN (in6[7]), .B (n_45), .Y (n_42));
  NOR2BX1 g197(.AN (in6[4]), .B (n_45), .Y (n_41));
  NOR2BX1 g196(.AN (in6[6]), .B (n_45), .Y (n_40));
  NOR2BX1 g199(.AN (in6[1]), .B (n_45), .Y (n_39));
  NAND2X4 g211(.A (n_13), .B (n_15), .Y (n_45));
  NOR2BX1 g216(.AN (in2[6]), .B (n_36), .Y (n_38));
  NOR2BX1 g212(.AN (in2[2]), .B (n_36), .Y (n_37));
  NOR2BX1 g213(.AN (in2[4]), .B (n_36), .Y (n_35));
  AOI22X1 g203(.A0 (in4[2]), .A1 (n_122), .B0 (in5[2]), .B1 (n_31), .Y
       (n_34));
  AOI22X1 g210(.A0 (in4[6]), .A1 (n_121), .B0 (in5[6]), .B1 (n_31), .Y
       (n_33));
  NOR2BX1 g217(.AN (in4[3]), .B (n_120), .Y (n_30));
  NOR2BX1 g218(.AN (in2[7]), .B (n_36), .Y (n_29));
  NOR2BX1 g219(.AN (in2[3]), .B (n_36), .Y (n_28));
  AOI22X1 g209(.A0 (in4[1]), .A1 (n_121), .B0 (in5[1]), .B1 (n_31), .Y
       (n_27));
  NOR2BX1 g223(.AN (in2[5]), .B (n_36), .Y (n_26));
  AOI22X1 g205(.A0 (in3[7]), .A1 (n_108), .B0 (in4[7]), .B1 (n_119), .Y
       (n_25));
  NOR2BX1 g226(.AN (in2[0]), .B (n_36), .Y (n_24));
  NOR2BX1 g228(.AN (in2[1]), .B (n_36), .Y (n_23));
  AOI22X1 g206(.A0 (in3[5]), .A1 (n_110), .B0 (in4[5]), .B1 (n_119), .Y
       (n_22));
  AOI22X1 g207(.A0 (in3[4]), .A1 (n_111), .B0 (in4[4]), .B1 (n_119), .Y
       (n_20));
  AOI22X1 g208(.A0 (in4[0]), .A1 (n_122), .B0 (in5[0]), .B1 (n_31), .Y
       (n_19));
  AOI22X1 g204(.A0 (in3[3]), .A1 (n_107), .B0 (in5[3]), .B1 (n_31), .Y
       (n_18));
  NAND2X1 g214(.A (in3[0]), .B (n_21), .Y (n_17));
  NAND2X1 g215(.A (in3[6]), .B (n_21), .Y (n_16));
  NOR2X2 g221(.A (n_7), .B (n_21), .Y (n_15));
  NAND2X1 g224(.A (in3[1]), .B (n_21), .Y (n_14));
  NOR2X2 g225(.A (n_31), .B (n_32), .Y (n_13));
  NAND2X1 g229(.A (in3[2]), .B (n_21), .Y (n_12));
  AND2XL g227(.A (in5[7]), .B (n_31), .Y (n_11));
  AND2XL g220(.A (in5[4]), .B (n_31), .Y (n_10));
  AND2XL g222(.A (in5[5]), .B (n_31), .Y (n_9));
  INVX1 g233(.A (n_7), .Y (n_36));
  NOR2X4 g232(.A (n_117), .B (n_3), .Y (n_32));
  NOR2X4 g234(.A (n_116), .B (n_5), .Y (n_7));
  NOR2X6 g235(.A (ctrl1[0]), .B (n_4), .Y (n_21));
  NOR2X6 g231(.A (ctrl1[0]), .B (n_1), .Y (n_31));
  NAND2X4 g237(.A (ctrl1[1]), .B (n_0), .Y (n_5));
  NAND2X6 g238(.A (ctrl1[2]), .B (n_2), .Y (n_4));
  NAND2X4 g239(.A (ctrl1[2]), .B (n_2), .Y (n_3));
  NAND2X6 g236(.A (ctrl1[2]), .B (ctrl1[1]), .Y (n_1));
  CLKINVX12 g241(.A (ctrl1[2]), .Y (n_0));
  CLKINVX12 g242(.A (ctrl1[1]), .Y (n_2));
  INVXL fopt(.A (n_109), .Y (n_107));
  INVXL fopt243(.A (n_109), .Y (n_108));
  INVXL fopt244(.A (n_21), .Y (n_109));
  INVXL fopt245(.A (n_112), .Y (n_110));
  INVXL fopt246(.A (n_112), .Y (n_111));
  INVXL fopt247(.A (n_21), .Y (n_112));
  CLKINVX4 fopt248(.A (ctrl1[0]), .Y (n_116));
  CLKINVX6 fopt249(.A (ctrl1[0]), .Y (n_117));
  CLKINVX1 fopt250(.A (n_120), .Y (n_119));
  CLKINVX1 fopt251(.A (n_120), .Y (n_121));
  CLKINVX1 fopt252(.A (n_120), .Y (n_122));
  CLKINVX1 fopt253(.A (n_32), .Y (n_120));
endmodule


