`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Apr 17 2022 21:30:54 CST (Apr 17 2022 13:30:54 UTC)

module dut_Add_3Ux2S_5S_1(in2, in1, out1);
  input [2:0] in2;
  input [1:0] in1;
  output [4:0] out1;
  wire [2:0] in2;
  wire [1:0] in1;
  wire [4:0] out1;
  wire add_23_2_n_0, add_23_2_n_1, add_23_2_n_3, add_23_2_n_4,
       add_23_2_n_5, add_23_2_n_6, add_23_2_n_7, add_23_2_n_8;
  wire add_23_2_n_10, add_23_2_n_11, add_23_2_n_12, add_23_2_n_15,
       add_23_2_n_16, add_23_2_n_18, add_23_2_n_27;
  MXI2X1 add_23_2_g69(.A (add_23_2_n_3), .B (in1[1]), .S0
       (add_23_2_n_18), .Y (out1[3]));
  NAND2X1 add_23_2_g70(.A (add_23_2_n_8), .B (add_23_2_n_16), .Y
       (add_23_2_n_18));
  MXI2XL add_23_2_g72(.A (add_23_2_n_10), .B (add_23_2_n_11), .S0
       (add_23_2_n_27), .Y (out1[2]));
  NAND2X2 add_23_2_g74(.A (add_23_2_n_0), .B (add_23_2_n_15), .Y
       (add_23_2_n_16));
  OAI21X4 add_23_2_g75(.A0 (add_23_2_n_5), .A1 (add_23_2_n_6), .B0
       (add_23_2_n_7), .Y (add_23_2_n_15));
  NAND2X1 add_23_2_g78(.A (in1[1]), .B (add_23_2_n_8), .Y
       (add_23_2_n_12));
  INVX1 add_23_2_g79(.A (add_23_2_n_10), .Y (add_23_2_n_11));
  NAND2X2 add_23_2_g80(.A (add_23_2_n_8), .B (add_23_2_n_0), .Y
       (add_23_2_n_10));
  MXI2XL add_23_2_g82(.A (add_23_2_n_4), .B (in2[0]), .S0 (in1[0]), .Y
       (out1[0]));
  NAND2X1 add_23_2_g83(.A (in2[2]), .B (in1[1]), .Y (add_23_2_n_8));
  NAND2X2 add_23_2_g85(.A (in2[1]), .B (in1[1]), .Y (add_23_2_n_7));
  NOR2X8 add_23_2_g86(.A (in2[1]), .B (in1[1]), .Y (add_23_2_n_6));
  NAND2X8 add_23_2_g88(.A (in2[0]), .B (in1[0]), .Y (add_23_2_n_5));
  INVX1 add_23_2_g89(.A (in2[0]), .Y (add_23_2_n_4));
  INVX2 add_23_2_g90(.A (in1[1]), .Y (add_23_2_n_3));
  NOR2BX1 add_23_2_g2(.AN (add_23_2_n_16), .B (add_23_2_n_12), .Y
       (out1[4]));
  NOR2BX1 add_23_2_g92(.AN (add_23_2_n_7), .B (add_23_2_n_6), .Y
       (add_23_2_n_1));
  NAND2BX4 add_23_2_g93(.AN (in2[2]), .B (add_23_2_n_3), .Y
       (add_23_2_n_0));
  XNOR2X1 add_23_2_g94(.A (add_23_2_n_5), .B (add_23_2_n_1), .Y
       (out1[1]));
  BUFX2 add_23_2_fopt(.A (add_23_2_n_15), .Y (add_23_2_n_27));
endmodule


