`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Apr 17 2022 22:24:04 CST (Apr 17 2022 14:24:04 UTC)

module dut_Lti8s5_4(in1, out1);
  input [4:0] in1;
  output out1;
  wire [4:0] in1;
  wire out1;
  NAND2BX1 gt_19_51_g128(.AN (in1[4]), .B (in1[3]), .Y (out1));
endmodule


