// Generated by stratus_hls 19.12-s100  (91710.131054)
// Sun Apr 17 22:24:13 2022
// from dut.cc
#include "dut_RAM_8X32_1.h"

struct dut_RAM_8X32_1;
dut_RAM_8X32_1::dut_RAM_8X32_1(sc_module_name name) : sc_module(name) 
    ,DIN("DIN")
    ,CE("CE")
    ,RW("RW")
    ,in1("in1")
    ,out1("out1")
    ,clk("clk")
    ,mem()
{
  SC_METHOD(dut_RAM_8X32_1_thread_1);
  sensitive << clk.pos();
  dont_initialize();

}
void dut_RAM_8X32_1::dut_RAM_8X32_1_thread_1(){
  if ( CE.read() ) {
    if ( RW.read() ) {
      (mem)[in1.read()] = DIN.read();
    } else {
      out1 = (mem)[in1.read()];
    }
  } else {
    out1 = 0ULL;
  }
}
