// Generated by stratus_hls 19.12-s100  (91710.131054)
// Sun Apr 17 22:24:13 2022
// from dut.cc

`timescale 1ps / 1ps

      
module dut_RAM_8X32_1(DIN, CE, RW, in1, out1, clk);

      input [31:0] DIN;
      input CE;
      input RW;
      input [2:0] in1;
      input clk;
      output [31:0] out1;
      reg [31:0] out1;
      reg[31:0] mem[7:0];

         // rtl_process:dut/dut_RAM_8X32_1_thread_1
         always @(posedge clk)
          begin :dut_RAM_8X32_1_thread_1
            if (CE) begin
               if (RW) begin
                  mem[in1] = DIN;
               end
               else begin
                  out1 <= mem[in1];
               end
            end
            else begin
               out1 <= 32'd0000000000;
            end
         end


endmodule


