`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Apr 17 2022 22:24:05 CST (Apr 17 2022 14:24:05 UTC)

module dut_Lti7s5_4(in1, out1);
  input [4:0] in1;
  output out1;
  wire [4:0] in1;
  wire out1;
  wire gt_19_51_n_0;
  OR2XL gt_19_51_g145(.A (in1[4]), .B (gt_19_51_n_0), .Y (out1));
  AOI31X1 gt_19_51_g146(.A0 (in1[1]), .A1 (in1[2]), .A2 (in1[0]), .B0
       (in1[3]), .Y (gt_19_51_n_0));
endmodule

